
package com.gallup.gethip.resources;

import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;

import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;

import com.gallup.gethip.DataSourceManager;
import com.gallup.gethip.model.systemtotal;
import com.j256.ormlite.dao.Dao;

// The Java class will be hosted at the URI path "/employee"
@Path("/totals")
public class systemTotalResource {

    // TODO: update the class to suit your needs
    
    // The Java method will process HTTP GET requests
    @GET 
    //will grab a JSON object with the system totals for that day
    //first will find the current day from the list, then will call that row number
    //will take the date as MMDDYYYY as the day param that will be the ID it will not be autogenerated. 
    @Produces("application/json")
    @Path("/{day}")
    public systemtotal getIt(@PathParam("day") String day) {
    	systemtotal records = new systemtotal(1, 52, 27, 256, 4232, 54654532, 15, 54, 25, 548, 215);
    	/*	try {
				records = getDao().queryForId(day);
				return records;
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				records = new systemtotal();
			}
			*/
    		return records;
    	
    }
    
    private Dao<systemtotal, String> getDao(){
    	Dao<systemtotal, String> dao = DataSourceManager.getInstance().getDao(systemtotal.class);
    	return dao;
    }
}
